# Generated by Django 4.2.26 on 2025-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='end_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='start_index',
            field=models.IntegerField(default=0),
        ),
    ]
