# Generated by Django 4.2.26 on 2025-11-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_note_end_index_note_start_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='select_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
